# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Flask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Python syntax for validate
        run: |
            python -m py_compile app.py
            python -m py_compile db.py

      - name: Start Flask application and run unit test for validate
        run: |
          python app.py &  # Запускаем Flask-приложение в фоновом режиме
          ake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          sleep 15  # Ждём 5 секунд, чтобы сервер успел запуститься
          run: pkill -f "python app.py" || true
